apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../base/
namespace: development
namePrefix: dev-
patchesStrategicMerge:
- replicas.yaml
images:
 -  name: nginx
    newTag: latest
